Develop
IlyaKZN/Fibonachi-school pull request #1
Opened 2022-06-14 01:01 UTC by IlyaKZN

2022-06-14 16:10 UTC, kyzinatra commented on src/components/string/string.tsx
> +
Надо исправить: Часть, которая отвеччает за реализацию самого алгоритма *(Но не его рендер)* должны быть **вынесены в отдельные файлы `utils.ts` в папке соответствующего компонента. При этом замечу, что функция реализующа алгоритм не долдна напрямую производить рендер. К примеру для строки это может выглядить примерно так:

```js

// utils.tsx

export function getReversingStringSteps(sourceString: string): string[][] {
// ...
}

export function getLetterState(/*...*/): ElementStates {

    return ElementStates.Modified;
// or
  
	return ElementStates.Changing;
// or

  return ElementStates.Default;
}

```

А в самом компоненте мы организуем рендер этой логики

```js

const startAlgorithm = () => {
const steps = getReversingStringSteps(sourceString);

if (steps.length) {
  intervalId = setInterval(() => {
    setCurrentAlgorithmStep(…);

…
  }, DELAY_IN_MS);
}

// Do not forget to clear interval after

};

return (…) // render

```

**По аналогии для всех компонентов реализации работы алгоритма**

2022-06-14 16:13 UTC, kyzinatra commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      </div>
Можно лучше: Преобразование к числу короче делать унарным плюсом: `+value`

2022-06-14 16:14 UTC, kyzinatra commented on src/components/fibonacci-page/fibonacci-page.tsx
> +        <Button disabled={Number(value) < 20 && Number(value) > 0 ? false : true} text="Рассчитать" onClick={() => onButtonClick(Number(value))} isLoader={algorithmState.inProgress} />
Можно лучше: мне кажется, что под `disabled` можно выделить отдельное состояние и при `onChange` инпута его менять, а не производить вычисления прямо тут

2022-06-14 16:15 UTC, kyzinatra commented on src/components/sorting-page/sorting-page.tsx
> +  const [currentStep, setCurrentStep] = useState<number>(0);
Надо исправить: При загрузке должен появляться случайный массив

2022-06-14 16:16 UTC, kyzinatra commented on src/components/sorting-page/sorting-page.tsx
> +  newArr: TDefaultButtonsState;
Отлично! Хорошая типизация

2022-06-14 16:17 UTC, kyzinatra commented on src/components/sorting-page/sorting-page.tsx
> +  };
Можно лучше: мне кажется более актуально использовать короткий интервал в сравнениях так как их достаточно много

2022-06-14 16:21 UTC, kyzinatra commented on src/components/queue-page/queue-page.tsx
> +              <Circle
Можно лучше: не стоит писать таку. функцию прямо в рендере. Вы можете делать тоже самое просто функцию самоу лучше вынести в тело функции

2022-06-14 16:31 UTC, kyzinatra commented on src/components/sorting-page/sorting-page.tsx
> +      //@ts-ignore
Можно лучше: лучше не использовать директиву `@ts-ignore`, вы можете сделать агруметы TColumnData не обязательными, используя `Partial<TColumnData>`. Насчет типов key можно посмотреть тут:
https://overcoder.net/q/2514639/%D1%82%D0%B8%D0%BF%D1%8B-%D0%B8%D0%B7-%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9-%D0%B8-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0-%D0%B2-typescript

2022-06-14 16:32 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Очень важно перенести все вычисления в `utils`
- При загрузке должен появляться случайный массив

Можно лучше:

- В хуке `useEffect` **(А также в любых функциях, что выполняют асинхронные действия)** вызывать `useState` стооит только если компонент действительно существует. Иначе, если выйти из страницы с неоконченным выполнением алгоритма возникает такая ошибка:

```sh

react_devtools_backend.js:4026 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
at StringComponent ([http://localhost:3000/static/js/bundle.js:2603:84](http://localhost:3000/static/js/bundle.js:2603:84))

```

Именно поэтому важно очищать все асинхронные запросы при размонтировании компонента. Это можно сделать примерно вот так:

```js

useEffect(() ⇒ {

let isComponentMounted = true;

await someAsyncStuff(() ⇒ {
if (isComponentMounted ) doMagic()

})

return  () ⇒ {isComponentMounted  = false};

})

```

Что понравилось:

- Хорошая типизация

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-06-14 17:35 UTC, kyzinatra commented
PS: Сразу не заметил, но тоже нужно исправить: Для очереди не высвечиваются элементы, добавляемые в head
<img width="718" alt="image" src="https://user-images.githubusercontent.com/51288221/173641026-4ffee050-9456-4c36-8fe6-3f3dceca04b2.png">

2022-06-14 22:59 UTC, IlyaKZN commented on src/components/string/string.tsx
> +
Добрый день, правильно я понимаю, что в случае со стеком, очередью и связным списком работа алгоритма происходит в соответствующих классах и я могу ничего в utils не выносить?

2022-06-15 15:45 UTC, kyzinatra commented
Надо исправить: Все еще не работает добавление элементов в связный список
<img width="627" alt="image" src="https://user-images.githubusercontent.com/51288221/173869955-ec96de14-b310-4ca3-8467-8f08d70a11b6.png">

При рендере value отмечается как `NaN`
<img width="470" alt="image" src="https://user-images.githubusercontent.com/51288221/173870383-81bc88b0-e26b-4f84-a862-77918321a1a0.png">


Если `input`  принимает строковые значения, то он должен и уметь их обрабатывать

2022-06-15 15:49 UTC, kyzinatra commented
Вы отлично потрудились! Осталось только исправить небольшие ошибки в связном списке и работа будет принята!

2022-06-16 08:20 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-07-06 06:15 UTC, merged